name = "Telperion"
uuid = "00bdae02-379d-4521-9e21-124662fe3143"
authors = ["joshday <emailjoshday@gmail.com> and contributors"]
version = "0.1.0"

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
